#!/bin/sh

#Works in gnome-terminal


#First start zookeeper server
gnome-terminal --title="zookeeper server" -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/zookeeper-server-start.sh /home/skalogerakis/kafka_2.12-2.4.0/config/zookeeper.properties;exec bash"
sleep 9

#Then start kafka server
gnome-terminal --title="kafka server" -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-server-start.sh /home/skalogerakis/kafka_2.12-2.4.0/config/server.properties;exec bash"
sleep 9

# /home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-server-stop.sh /home/skalogerakis/kafka_2.12-2.4.0/config/server.properties
#delete old topics
# gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic TestOut"
# sleep 5
gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic input"
sleep 5
gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic output"
sleep 7

# /home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic input-topic-job1
# /home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --list --bootstrap-server localhost:9092

#Create new topic 
# gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic TestOut;exec bash"
# sleep 3
gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic input;exec bash"
sleep 3
gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic output;exec bash"
sleep 5

#Open and view messages in a new terminal
# producer /home/john/kafka_2.12-2.3.0/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test ////{"word":"a","value":"3"} {"word":"a","value2":"1"}
#gnome-terminal -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic TestTopic --from-beginning;exec bash"

# gnome-terminal --title="TestOut_consumer" -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic TestOut --from-beginning;exec bash "
# sleep 2
gnome-terminal --title="Input_consumer" -- bash -c "/home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic input --from-beginning;exec bash "
sleep 2
gnome-terminal --title="Output_consumer" -- bash -c " /home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic output --from-beginning;exec bash"
sleep 2
gnome-terminal --title="Input_producer" -- bash -c " /home/skalogerakis/kafka_2.12-2.4.0/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic input --property \"parse.key=true\" --property \"key.separator=:\";exec bash"


#{"key":"a","value":"3"}